name: Build TWRP (AOSP) for TALIH-PD1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP
    runs-on: ubuntu-latest

    env:
      TZ: "Asia/Shanghai"
      DEVICE: tb8788p1_64_wifi
      OUTDIR: ${{ github.workspace }}/out

    steps:
    - name: Checkout device tree
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison gperf build-essential \
        zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
        lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
        ccache libgl1-mesa-dev libxml2-utils xsltproc unzip python3 python3-pip \
        libncurses5-dev

    - name: Setup repo (AOSP TWRP)
      run: |
        mkdir -p ~/android/twrp
        cd ~/android/twrp
        repo init -u https://github.com/TeamWin/android_bootable_recovery.git -b twrp-12.1
        repo sync -c -j8 --no-clone-bundle --no-tags

    - name: Copy device tree
      run: |
        mkdir -p ~/android/twrp/device/alps/$DEVICE
        cp -r $GITHUB_WORKSPACE/* ~/android/twrp/device/alps/$DEVICE/

    - name: Setup environment
      run: |
        cd ~/android/twrp
        source build/envsetup.sh
        lunch omni_$DEVICE-eng

    - name: Build TWRP recovery
      run: |
        cd ~/android/twrp
        mka recoveryimage -j$(nproc)

    - name: Upload recovery image
      uses: actions/upload-artifact@v3
      with:
        name: twrp_recovery
        path: ~/android/twrp/out/target/product/$DEVICE/recovery.img
