name: Build TWRP (AOSP) for TALIH-PD1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP
    runs-on: ubuntu-22.04

    env:
      TZ: "Asia/Shanghai"
      DEVICE: tb8788p1_64_wifi
      OUTDIR: ${{ github.workspace }}/out

    steps:
    - name: Checkout device tree
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386 || true
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential curl flex g++ gcc git gnupg gperf \
          libncurses-dev libssl-dev python3 python3-pip unzip xz-utils zip \
          wget rsync lzop ccache curl repo

    - name: Setup repo (AOSP TWRP)
      run: |
        mkdir -p ~/android/twrp
        cd ~/android/twrp
        repo init -u https://github.com/TeamWin/android_bootable_recovery.git -b twrp-12.1
        repo sync -c -j8 --no-clone-bundle --no-tags

    - name: Copy device tree
      run: |
        mkdir -p ~/android/twrp/device/alps/$DEVICE
        cp -r $GITHUB_WORKSPACE/* ~/android/twrp/device/alps/$DEVICE/

    - name: Setup environment
      run: |
        cd ~/android/twrp
        source build/envsetup.sh
        lunch omni_$DEVICE-eng

    - name: Build TWRP recovery
      run: |
        cd ~/android/twrp
        mka recoveryimage -j$(nproc)

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp_recovery
        path: ~/android/twrp/out/target/product/$DEVICE/recovery.img
